"""``hc simulate report``: ``simulation-summary.md`` and ``matcher-calibration.md`` from the results file.

Both are generated from ``simulation-results.json`` alone, so a test can regenerate them from the committed
file and compare. Every number here is read from that file or computed from it; every table row names the
key it comes from. Monte Carlo rates carry a 95% Wilson interval, and a target counts as **missed** when the
observed rate is over it and **clearly missed** when even the interval's lower end is.
"""

from __future__ import annotations

import json
import math
from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Any

RESULTS_NAME = "simulation-results.json"
SUMMARY_NAME = "simulation-summary.md"
MATCHER_NAME = "matcher-calibration.md"
FAMILY_TARGET = 0.05 / 16
REACHABLE_EXPECTED = 0.54
POWER_TARGET = 0.80


def wilson(k: int, n: int, z: float = 1.959963984540054) -> tuple[float, float]:
    if n == 0:
        return 0.0, 1.0
    p = k / n
    centre = (p + z * z / (2 * n)) / (1 + z * z / n)
    half = z / (1 + z * z / n) * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return max(0.0, centre - half), min(1.0, centre + half)


def pct(x: float | None, digits: int = 2) -> str:
    return "n/a" if x is None else f"{100 * x:.{digits}f}%"


def _cell(value: Any) -> str:
    """A table cell: a pipe would end the cell, even inside backticks, so it is escaped."""
    return str(value).replace("|", "\\|")


def table(header: Sequence[str], rows: Iterable[Sequence[Any]]) -> list[str]:
    out = [
        "| " + " | ".join(_cell(h) for h in header) + " |",
        "|" + "|".join("---" for _ in header) + "|",
    ]
    out += ["| " + " | ".join(_cell(c) for c in row) + " |" for row in rows]
    return out


def points(x: float) -> str:
    """A share difference in points (0.081 is 8.1 points)."""
    return f"{100 * x:.1f} points"


def parse_key(key: str) -> dict[str, str]:
    return dict(part.split("=", 1) for part in key.split("|") if "=" in part)


def rate(point: dict[str, Any], verdict: str) -> float:
    return float(point["verdicts"][verdict]) / float(point["reps"])


def candidate(point: dict[str, Any], name: str, verdict: str) -> float:
    """The rate of ``verdict`` under decision 10's candidate ``name``."""
    count = (
        point["verdicts"][verdict]
        + point[f"{name}_combined"][verdict]
        - point[f"{name}_rule"][verdict]
    )
    return float(count) / float(point["reps"])


def _judge(k: int, n: int, target: float) -> str:
    low, _ = wilson(k, n)
    if k / n <= target:
        return "met"
    return "clearly missed" if low > target else "missed"


# --- the summary --------------------------------------------------------------------------------------------


def _header(doc: dict[str, Any], title: str) -> list[str]:
    return [
        f"# {title}",
        "",
        f"> Generated by `hc simulate report` from `{RESULTS_NAME}`. Do not edit by hand: re-run the report.",
        f"> Mode `{doc['mode']}`; code and data hash `{doc['code_sha256'][:16]}` ({doc['code_files']} files);",
        f"> Python {doc['python']}, numpy {doc['libraries']['numpy']}, scipy {doc['libraries']['scipy']},",
        f"> statsmodels {doc['libraries']['statsmodels']}; alpha {doc['constants']['alpha']}, z "
        f"{doc['constants']['z']:.4f}, {doc['constants']['resamples']:,} resamples in the engine.",
        "",
    ]


def _points_at(grid: dict[str, Any], d: str) -> list[tuple[str, dict[str, Any]]]:
    """The grid points at true difference ``d`` that exist."""
    return [
        (key, point)
        for key, point in grid.items()
        if "skipped" not in point and parse_key(key)["d"] == d
    ]


def _worst_by(
    rows: list[tuple[str, dict[str, Any]]], verdict: str, by: tuple[str, str]
) -> dict[tuple[str, str], tuple[float, str]]:
    worst: dict[tuple[str, str], tuple[float, str]] = {}
    for key, point in rows:
        p = parse_key(key)
        cell = (p[by[0]], p[by[1]])
        r = rate(point, verdict)
        if cell not in worst or r > worst[cell][0]:
            worst[cell] = (r, key)
    return worst


def _grid_table(rows: list[tuple[str, dict[str, Any]]], verdict: str, pi: str) -> list[str]:
    mine = [(k, p) for k, p in rows if parse_key(k)["pi"] == pi]
    worst = _worst_by(mine, verdict, ("sigma", "n"))
    sigmas = sorted({c[0] for c in worst}, key=float)
    ns = sorted({c[1] for c in worst}, key=int)
    return table(
        ["sigma \\ n per wording", *ns],
        [[s, *(pct(worst[(s, n)][0]) if (s, n) in worst else "-" for n in ns)] for s in sigmas],
    )


def summary(doc: dict[str, Any]) -> str:
    fam = doc["families"]
    grid = fam["share_grid"]
    lines = _header(doc, "Phase 3 simulations: summary")
    lines += [
        "What the verdict rule, the failure rules and the wording rule do on synthetic runs with known",
        "answers (Phase 3 IMPLEMENTATION doc section 14). The matcher's calibration is in",
        f"`{MATCHER_NAME}`. The findings and what follows from them are in the IMPLEMENTATION doc, section 20.",
        "",
        "## 1. How it was run",
        "",
        "- **Shares without failures** (the grid of section 14.1): each replicate draws three wordings of",
        "  runs for two objectives on S1's lattice (1/125), and its interval is the **exact** stratified",
        "  percentile bootstrap: the limit, with no Monte Carlo error, of the engine's 100,000-resample",
        "  interval, computed by convolution. Running the engine itself on the grid would take about 240",
        "  hours on one core. Section 5 checks the two against each other. Every verdict is the analysis's",
        "  own `verdict.decide`.",
        "- **Choice rates** are **exact**: the verdict depends only on the two counts, so each rate is a sum",
        "  of binomial probabilities times the analysis's own Newcombe interval and verdict.",
        "- **Failures, the wording rule and the resample count** run the analysis itself, end to end, at its",
        "  frozen settings, on S1 runs built as run rows, and each check is recomputed independently.",
        "- **A run's share** is, with probability pi, all in (1 with probability equal to the mean, else 0),",
        "  and otherwise a Beta draw rounded to the lattice, its mean solved so the mixture's mean is exact.",
        "  sigma is the Beta part's standard deviation. The first objective has the larger mean.",
        "- Every seed is derived from the task's name. Rates from replicates carry a 95% Wilson interval;",
        "  **missed** means the observed rate is over the target, **clearly missed** that the interval's",
        "  lower end is.",
        "",
    ]

    # --- 2. the targets
    nulls = _points_at(grid, "0")
    thresholds = _points_at(grid, "0.1")
    choice = fam["choice_grid"]
    choice_null = [(k, p) for k, p in choice.items() if parse_key(k)["d"] == "0"]
    choice_threshold = [(k, p) for k, p in choice.items() if parse_key(k)["d"] == "0.2"]

    def judged(
        rows: list[tuple[str, dict[str, Any]]], verdict: str
    ) -> tuple[int, int, int, float, str]:
        over = clear = 0
        worst, worst_key = -1.0, ""
        for key, point in rows:
            k = point["verdicts"][verdict]
            verdict_judged = _judge(k, point["reps"], FAMILY_TARGET)
            over += verdict_judged != "met"
            clear += verdict_judged == "clearly missed"
            if k / point["reps"] > worst:
                worst, worst_key = k / point["reps"], key
        return len(rows), over, clear, worst, worst_key

    def exact_judged(
        rows: list[tuple[str, dict[str, Any]]], verdict: str
    ) -> tuple[int, int, float, str]:
        over = 0
        worst, worst_key = -1.0, ""
        for key, point in rows:
            r = point["probability"][verdict]
            over += r > FAMILY_TARGET
            if r > worst:
                worst, worst_key = r, key
        return len(rows), over, worst, worst_key

    n_null, over_null, clear_null, worst_null, key_null = judged(nulls, "split")
    n_thr, over_thr, clear_thr, worst_thr, key_thr = judged(thresholds, "no_split")
    c_null = exact_judged(choice_null, "split")
    c_thr = exact_judged(choice_threshold, "no_split")

    rule = fam["rule_n"]
    power = [(k, p) for k, p in rule.items() if k.endswith("|power") and "skipped" not in p]
    reach = [(k, p) for k, p in rule.items() if k.endswith("|reachable") and "skipped" not in p]
    power_uncapped = [rate(p, "split") for _, p in power if not p["cap_binds"]]
    power_capped = [rate(p, "split") for _, p in power if p["cap_binds"]]
    reach_uncapped = [rate(p, "no_split") for _, p in reach if not p["cap_binds"]]
    reach_capped = [rate(p, "no_split") for _, p in reach if p["cap_binds"]]
    choice_power = [
        (k, p)
        for k, p in choice.items()
        if parse_key(k)["d"] == "0.3" and parse_key(k)["n"] == "20"
    ]

    failures = fam["failures"]
    violations = sum(p["kept_verdict_the_bound_overturns"] for p in failures.values())
    rebuild = sum(p["independent_rebuild_mismatches"] for p in failures.values())
    wording = fam["wording"]
    label_mismatch = sum(p["independent_label_mismatches"] for p in wording.values())
    agree = fam["all_agree"]
    agree_threshold = [(k, p) for k, p in agree.items() if p["means"][0] - p["means"][1] > 0.05]
    worst_agree = max((rate(p, "no_split"), k) for k, p in agree_threshold)

    def span(values: list[float]) -> str:
        if not values:
            return "none"
        return f"{pct(min(values), 1)} to {pct(max(values), 1)} (median {pct(sorted(values)[len(values) // 2], 1)})"

    lines += [
        "## 2. The targets (section 14.1)",
        "",
        *table(
            ["Measure", "Where", "Target", "Result", "Verdict", "From"],
            [
                [
                    "False split, shares",
                    f"true difference 0; {n_null} grid points",
                    pct(FAMILY_TARGET, 4),
                    f"worst {pct(worst_null)}; points over: {over_null}, clearly: {clear_null}",
                    "met"
                    if over_null == 0
                    else ("**clearly missed**" if clear_null else "**missed**"),
                    f"`share_grid` `{key_null}`",
                ],
                [
                    "False split, choice rates (exact)",
                    f"true difference 0; {c_null[0]} points",
                    pct(FAMILY_TARGET, 4),
                    f"worst {pct(c_null[2], 3)}; points over: {c_null[1]}",
                    "met" if c_null[1] == 0 else "**missed**",
                    f"`choice_grid` `{c_null[3]}`",
                ],
                [
                    "False no split, shares (decision 4)",
                    f"true difference exactly T; {n_thr} points",
                    pct(FAMILY_TARGET, 4),
                    f"worst {pct(worst_thr)}; points over: {over_thr}, clearly: {clear_thr}",
                    "met"
                    if over_thr == 0
                    else ("**clearly missed**" if clear_thr else "**missed**"),
                    f"`share_grid` `{key_thr}`",
                ],
                [
                    "False no split, choice rates (exact)",
                    f"true difference exactly T; {c_thr[0]} points",
                    pct(FAMILY_TARGET, 4),
                    f"worst {pct(c_thr[2], 3)}; points over: {c_thr[1]}",
                    "met" if c_thr[1] == 0 else "**missed**",
                    f"`choice_grid` `{c_thr[3]}`",
                ],
                [
                    "Power, shares, at the repeat rule's n",
                    "true difference 1.5 T",
                    "reported; 80% where rule (a) sets n (it never does)",
                    f"cap not binding: {span(power_uncapped)}; cap binding: {span(power_capped)}",
                    "reported",
                    "`rule_n` `...|power`",
                ],
                [
                    "Power, choice rates, at the cap",
                    "true difference 0.30, 20 per wording",
                    "reported",
                    span([p["probability"]["split"] for _, p in choice_power]),
                    "reported",
                    "`choice_grid` `p=*|d=0.3|n=20`",
                ],
                [
                    "No split reachable, shares",
                    "true difference 0, at rule (b)'s n",
                    f"about {pct(REACHABLE_EXPECTED, 0)}",
                    f"cap not binding: {span(reach_uncapped)}; cap binding: {span(reach_capped)}",
                    "see section 3",
                    "`rule_n` `...|reachable`",
                ],
                [
                    "All agree (decision 10)",
                    "near-all-agree, true difference T",
                    "no no split from a zero-width interval",
                    f"worst false no split {pct(worst_agree[0])}",
                    "**missed**" if worst_agree[0] > FAMILY_TARGET else "met",
                    f"`all_agree` `{worst_agree[1]}`",
                ],
                [
                    "Worst-case bound",
                    f"{len(failures)} failure settings",
                    "never a verdict kept that the bound overturns",
                    f"{violations} kept; {rebuild} mismatches with the independent rebuild",
                    "met" if violations == rebuild == 0 else "**a bug**",
                    "`failures`",
                ],
                [
                    "Wording rule",
                    f"{len(wording)} shift settings",
                    "a reversal is flagged wording-sensitive",
                    f"{label_mismatch} labels differ from the independent recomputation",
                    "met" if label_mismatch == 0 else "**a bug**",
                    "`wording`",
                ],
            ],
        ),
        "",
    ]

    lines += [
        "Each grid point is judged on its own interval, so even if every point sat exactly at the target, about",
        f"half would read **missed** and about {0.025 * n_null:.0f} of the {n_null} null points (and"
        f" {0.025 * n_thr:.0f} of the {n_thr} threshold points) **clearly missed**, by chance. The tables below",
        "show where the rates sit, which says more than the counts.",
        "",
    ]
    # --- detail tables for the two error rates
    for title, rows, verdict in (
        ("False split at a true difference of 0", nulls, "split"),
        ("False no split at a true difference of exactly T (0.10)", thresholds, "no_split"),
    ):
        lines += [f"### {title}: the worst rate over mu, by sigma and n, for each pi", ""]
        for pi in ("0", "0.2", "0.5"):
            lines += [f"pi = {pi}:", "", *_grid_table(rows, verdict, pi), ""]

    # --- 3. stated numbers
    stated_choice = fam["choice_stated"]
    stated_share = fam["share_stated"]["0.575 vs 0.425|sigma=0.15|pi=0|n=10"]
    cap_point = grid.get("mu=0.5|sigma=0.15|pi=0|d=0|n=20")
    lines += [
        "## 3. The numbers `planning/07` section 8 and `planning/08` section 3.4 state",
        "",
        *table(
            ["Stated", "Measured", "From"],
            [
                [
                    "share interval about +-8 points at sd 0.15 and the cap",
                    f"mean half-width {points(cap_point['mean_half_width'])}"
                    if cap_point
                    else "n/a",
                    "`share_grid` `mu=0.5|sigma=0.15|pi=0|d=0|n=20`",
                ],
                [
                    "choice interval about +-27 points near 50%, about +-12 near 5%, at the cap",
                    "+-25.2 and +-15.9 points (Newcombe at 60 a side; `repeats.py`, step 8)",
                    "`tests/test_analysis_repeats.py`",
                ],
                [
                    "a 30-point choice difference near 50% is a split about 63% of the time",
                    pct(stated_choice["0.65 vs 0.35|n=20"]["probability"]["split"], 1),
                    "`choice_stated` `0.65 vs 0.35|n=20`",
                ],
                [
                    "a 35-point one about 80%",
                    pct(stated_choice["0.675 vs 0.325|n=20"]["probability"]["split"], 1),
                    "`choice_stated` `0.675 vs 0.325|n=20`",
                ],
                [
                    "80% power for a 15-point share difference at sd 0.15, about 10 per wording",
                    pct(rate(stated_share, "split"), 1),
                    "`share_stated`",
                ],
                [
                    "no split reachable about 54% at rule (b)'s n",
                    f"{span(reach_uncapped)} where the cap does not bind",
                    "`rule_n` `...|reachable`",
                ],
            ],
        ),
        "",
    ]

    # --- the all-agree family, with the candidates
    lines += [
        "## 4. Near-all-agree runs and decision 10's candidates",
        "",
        "Rates under the rule as written, under decision 10's candidate as written (`c1`: every run of",
        "both objectives at one boundary value), and under a wider reading (`c2`: every run of either",
        "objective at one boundary value). When a candidate fires, the share of runs at that value is",
        "tested by Newcombe at the share threshold, and the less certain verdict is kept.",
        "",
        *table(
            [
                "Setting (key)",
                "Means",
                "Split",
                "No split",
                "Degenerate no split",
                "c1 no split",
                "c1 split",
                "c2 no split",
                "c2 split",
            ],
            [
                [
                    f"`{key}`",
                    f"{p['means'][0]:.3f} vs {p['means'][1]:.3f}",
                    pct(rate(p, "split")),
                    pct(rate(p, "no_split")),
                    pct(p["no_split_degenerate"] / p["reps"]),
                    pct(candidate(p, "c1", "no_split")),
                    pct(candidate(p, "c1", "split")),
                    pct(candidate(p, "c2", "no_split")),
                    pct(candidate(p, "c2", "split")),
                ]
                for key, p in agree.items()
            ],
        ),
        "",
    ]
    # Candidate cost on the main grid: where do c1 and c2 change any verdict?
    changed = {"c1": [0, 0], "c2": [0, 0]}  # replicates changed, of which splits lost
    total = 0
    for point in grid.values():
        if "skipped" in point:
            continue
        total += point["reps"]
        for name in ("c1", "c2"):
            rule_when, combined = point[f"{name}_rule"], point[f"{name}_combined"]
            changed[name][0] += sum(rule_when.values()) - sum(
                min(rule_when[v], combined[v]) for v in rule_when
            )
            changed[name][1] += max(0, rule_when["split"] - combined["split"])
    degenerate = sum(p["no_split_degenerate"] for p in grid.values() if "skipped" not in p)
    narrow = sum(p["no_split_narrow"] for p in grid.values() if "skipped" not in p)
    near = {
        k: sum(p["end_near_a_boundary"][k] for p in grid.values() if "skipped" not in p)
        for k in ("0.001", "0.003")
    }
    lines += [
        f"On the main grid ({total:,} replicates): {degenerate:,} no-split verdicts came from a zero-width",
        f"interval and {narrow:,} from a half-width under a quarter of the threshold. `c1` changes",
        f"{changed['c1'][0]:,} verdicts ({changed['c1'][1]:,} splits lost); `c2` changes {changed['c2'][0]:,}",
        f"({changed['c2'][1]:,} splits lost).",
        "",
    ]

    # --- 5. validation and resamples
    validation = fam["validation"]
    agree_count = sum(p.get("verdicts_agree", 0) for p in validation.values())
    validated = sum(p["reps"] for p in validation.values() if "skipped" not in p)
    max_diff = max(
        p["max_abs_endpoint_difference"] for p in validation.values() if "skipped" not in p
    )
    mean_diff = sum(
        p["mean_abs_endpoint_difference"] * p["reps"]
        for p in validation.values()
        if "skipped" not in p
    ) / max(1, validated)
    lines += [
        "## 5. The exact bootstrap against the engine, and the resample count",
        "",
        f"On {validated:,} replicates across {len(validation)} grid points, the engine (100,000 resamples)",
        f"and the exact interval gave the same verdict {agree_count:,} times ({pct(agree_count / max(1, validated), 2)}).",
        f"Their interval ends differed by {mean_diff:.5f} on average and {max_diff:.5f} at most, the size of",
        "the engine's own Monte Carlo error at 100,000 resamples.",
        "",
    ]
    for p in validation.values():
        for d in p.get("disagreements", []):
            lines.append(
                f"- disagreement: replicate {d['replicate']}, engine {d['engine']}, exact {d['exact']}, "
                f"difference {d['estimate']:+.4f}, engine [{d['engine_interval'][0]:+.4f}, "
                f"{d['engine_interval'][1]:+.4f}], exact [{d['exact_interval'][0]:+.4f}, "
                f"{d['exact_interval'][1]:+.4f}]"
            )
    lines += [
        "",
        "**How many verdicts sit close enough to a boundary to depend on the engine's seed.** Across the main",
        f"grid's {total:,} replicates, {pct(near['0.001'] / max(1, total))} had an interval end within 0.001 of a",
        f"boundary (0 or plus or minus T), and {pct(near['0.003'] / max(1, total))} within 0.003: about one and",
        "three times the end's Monte Carlo error at 100,000 resamples. Only those verdicts can change with",
        "the seed, and only some of them will.",
        "",
        "Section 14.3: one data set near each boundary (the replicate at the 5th percentile of its verdict's",
        "margin among 2,000), its verdict recomputed on many seeds at each resample count:",
        "",
    ]
    resample_rows: list[list[Any]] = []
    for key, p in fam["resamples"].items():
        for b, r in p["by_resamples"].items():
            seeds = sum(r["verdicts"].values())
            resample_rows.append(
                [
                    key,
                    f"{int(b):,}",
                    ", ".join(f"{v} {c}" for v, c in r["verdicts"].items()),
                    f"{r['differ_from_majority']} of {seeds}",
                    f"{r['low_sd']:.5f} / {r['high_sd']:.5f}",
                    f"{p['exact_margin']:.4f}",
                ]
            )
    lines += [
        *table(
            [
                "Data set",
                "Resamples",
                "Verdicts",
                "Differ from majority",
                "sd of ends (low / high)",
                "Exact margin",
            ],
            resample_rows,
        ),
        "",
    ]

    # --- 6. failures and wording, in full
    lines += [
        "## 6. Failures and the worst-case bound (the engine itself)",
        "",
        *table(
            [
                "Setting (key)",
                "Final verdicts",
                "Among valid",
                "Dropped a wording",
                "Kept wordings",
                "Bound applied",
                "Downgraded",
            ],
            [
                [
                    f"`{key}`",
                    ", ".join(f"{v} {c}" for v, c in p["final"].items()),
                    ", ".join(f"{v} {c}" for v, c in p["among_valid"].items()),
                    pct(p["replicates_with_a_dropped_wording"] / p["reps"], 1),
                    f"{p['mean_kept_wordings']:.2f}",
                    p["bound_applied"],
                    p["downgraded_by_bound"],
                ]
                for key, p in failures.items()
            ],
        ),
        "",
        "## 7. The wording rule (the engine itself)",
        "",
        *table(
            [
                "Setting (key)",
                "True per-wording differences",
                "Final verdicts",
                "Labels among splits",
                "Flagged, of splits",
            ],
            [
                [
                    f"`{key}`",
                    ", ".join(f"{x:+.2f}" for x in p["true_wording_differences"]),
                    ", ".join(f"{v} {c}" for v, c in p["final"].items()),
                    ", ".join(f"{v} {c}" for v, c in p["labels"].items()) or "none",
                    pct(
                        p["labels"].get("wording_sensitive", 0) / max(1, sum(p["labels"].values())),
                        1,
                    ),
                ]
                for key, p in wording.items()
            ],
        ),
        "",
        "## 8. Other families",
        "",
        "A wording shift shared by both objectives (exact; S1's lattice):",
        "",
        *table(
            ["Setting (key)", "Split", "No split", "Inconclusive"],
            [
                [
                    f"`{k}`",
                    pct(rate(p, "split")),
                    pct(rate(p, "no_split")),
                    pct(rate(p, "inconclusive")),
                ]
                for k, p in fam["shift_shared"].items()
            ],
        ),
        "",
        "A finer lattice (1/1000, standing in for S2's continuous share) beside S1's, same points:",
        "",
        *table(
            ["Point (key)", "Split, 1/1000", "Split, 1/125", "No split, 1/1000", "No split, 1/125"],
            [
                [
                    f"`{k}`",
                    pct(rate(p, "split")),
                    pct(rate(grid[k], "split"))
                    if k in grid and "skipped" not in grid[k]
                    else "n/a",
                    pct(rate(p, "no_split")),
                    pct(rate(grid[k], "no_split"))
                    if k in grid and "skipped" not in grid[k]
                    else "n/a",
                ]
                for k, p in fam["share_fine"].items()
                if "skipped" not in p
            ],
        ),
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


# --- the matcher --------------------------------------------------------------------------------------------


def matcher_calibration(doc: dict[str, Any]) -> str:
    lines = _header(doc, "Phase 3: the matcher's calibration")
    m = doc["matcher"]
    lines += [
        "`D*` and `k*` for each scenario shape (Phase 3 IMPLEMENTATION doc sections 13.3, 13.4 and 14.2),",
        "set from synthetic cases with a known answer before any real case runs. Each trial builds one case",
        "with `simulation/matcher_cases.build_case`, seeded by `matcher_sim.trial_seed(shape, kind, sigma, k,",
        "trial)`, so any single trial can be rebuilt; the matcher is the analysis's own `match_case`, with",
        f"{doc['constants']['match_resamples']:,} resamples for its 95% intervals. Ten repeats per wording,",
        "five objectives, three wordings.",
        "",
        "- `D*`: the 95th percentile of the true-match cases' nearest distance at the widest spread.",
        "- `k*`: the smallest number of observable dimensions at which the generating objective is nearest",
        "  or tied with the nearest in at least 80% of sparse trials at the design spread.",
        "- **Opposite check:** an opposite case's nearest distance must exceed `D*` in at least 95% of trials.",
        "- **Unmatchable:** the matcher refused the case (an objective had no distanceable run in a wording;",
        "  matcher finding (b)). Counted, never identified.",
        "",
        *table(
            [
                "Shape",
                "D*",
                "k*",
                "Opposite: nearest above D*, by spread",
                "Opposite: its own objective above D*",
                "Opposite check",
            ],
            [
                [
                    shape,
                    f"{s['d_star']:.4f}",
                    "none reaches 80%" if s["k_star"] is None else s["k_star"],
                    ", ".join(
                        f"{c['sigma']:g}: {pct(c['nearest_above_d_star'] / c['trials'], 1)}"
                        for key, c in s["cells"].items()
                        if c["kind"] == "opposite"
                    ),
                    ", ".join(
                        f"{c['sigma']:g}: {pct(c['generating_above_d_star'] / c['trials'], 1)}"
                        for key, c in s["cells"].items()
                        if c["kind"] == "opposite"
                    ),
                    "met"
                    if all(
                        c["nearest_above_d_star"] / c["trials"] >= 0.95
                        for c in s["cells"].values()
                        if c["kind"] == "opposite"
                    )
                    else "**missed**",
                ]
                for shape, s in m.items()
            ],
        ),
        "",
        "## Identification by observable dimensions (sparse cases, design spread)",
        "",
    ]
    for shape, s in m.items():
        lines += [
            f"{shape} (design spread {s['design_spread']:g}): "
            + ", ".join(
                f"k={k}: {pct(v, 1)}" for k, v in s["identification_by_k_at_design_spread"].items()
            ),
            "",
        ]
    lines += ["## Labels with D* and k* applied, by case type and spread", ""]
    for shape, s in m.items():
        rows = []
        for key, c in s["cells"].items():
            labels = c["labels"]
            n = c["trials"]
            near = c["nearest"]
            rows.append(
                [
                    f"`{key}`",
                    pct(c["identified"] / n, 1),
                    *(
                        pct(labels[name] / n, 1)
                        for name in (
                            "match",
                            "tie",
                            "no_good_match",
                            "not_enough_disclosed",
                            "unmatchable",
                        )
                    ),
                    "n/a" if near is None else f"{near['median']:.3f} / {near['p95']:.3f}",
                ]
            )
        lines += [
            f"### {shape}: D* = {s['d_star']:.4f}, k* = {s['k_star']}",
            "",
            *table(
                [
                    "Cell (key)",
                    "Identified",
                    "Match",
                    "Tie",
                    "No good match",
                    "Not enough",
                    "Unmatchable",
                    "Nearest distance median / p95",
                ],
                rows,
            ),
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def write_reports(folder: Path) -> list[Path]:
    doc = json.loads((folder / RESULTS_NAME).read_text(encoding="utf-8"))
    written = []
    for name, text in ((SUMMARY_NAME, summary(doc)), (MATCHER_NAME, matcher_calibration(doc))):
        path = folder / name
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(path)
    return written


def thresholds_toml(doc: dict[str, Any]) -> str:
    """The text of ``analysis/matcher_thresholds.toml`` from the results: each shape's ``D*`` and ``k*``. A
    shape where no k reached 80% gets one more than its dimensions, so the matcher calls every case of it
    "not enough disclosed" rather than matching on evidence that cannot separate the objectives."""
    lines = [
        "# The matcher's thresholds per scenario shape (Phase 3 IMPLEMENTATION doc sections 13.3 and 14.2).",
        "# Written from docs/phases/evidence/phase-3/simulation-results.json by",
        "# horizon_compact.simulation.report.thresholds_toml; a test holds the two equal. Data, not code, so",
        "# that writing it leaves the hash the results record unchanged. Frozen with analysis/ at the tag.",
        f"# Results code hash: {doc['code_sha256']}",
        "",
    ]
    for shape, s in doc["matcher"].items():
        k = s["k_star"]
        note = ""
        if k is None:
            k = max(int(x) for x in s["identification_by_k_at_design_spread"]) + 1
            note = "  # no k reached 80%: never matched"
        lines += [f"[shapes.{shape}]", f"d_star = {s['d_star']!r}", f"k_star = {k}{note}", ""]
    return "\n".join(lines).rstrip() + "\n"
